ARG IMAGE_OS_VERSION=ltsc2022
FROM mcr.microsoft.com/windows/servercore:${IMAGE_OS_VERSION} AS download

SHELL ["powershell", "-Command"]

# Retrieve msys2
RUN \
    if(!(Test-Path -Path 'C:\Temp')) \
    { \
        New-Item \
            -Path 'C:\Temp' \
            -ItemType Directory \
            -Verbose ; \
    } ; \
    \
    Invoke-WebRequest \
        -Uri $('https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe') \
        -OutFile $('C:\Temp\msys2-base.exe') \
        -UseBasicParsing \ 
        -Verbose ; \
    \
    Start-Process \
        -FilePath $('C:\Temp\msys2-base.exe') \
        -ArgumentList '-y -oC:\Temp\' \
        -NoNewWindow \
        -Wait \
        -Verbose ; \
    \
    Remove-Item \
        -Path 'C:\Temp\msys2-base.exe' \
        -Verbose ;

RUN dir
RUN dir windows\system32

FROM mcr.microsoft.com/windows/nanoserver:${IMAGE_OS_VERSION}

RUN dir
RUN dir windows\system32

# COPY --from=download ["/temp/msys64", "/msys64"]


# In order to set system PATH, ContainerAdministrator must be used
USER ContainerAdministrator
RUN setx /M PATH "%PATH%;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl"

USER ContainerUser

COPY win32u.dll /Windows/System32/
COPY gdi32full.dll /Windows/System32/
# COPY msvcp_win.dll /Windows/System32/


COPY --from=download ["/windows/system32/kernel32.dll", "/windows/system32/kernel32.dll"]
COPY --from=download ["/windows/system32/user32.dll", "/windows/system32/user32.dll"]
COPY --from=download ["/windows/system32/gdi32.dll", "/windows/system32/gdi32.dll"]

COPY --from=download ["/windows/system32/netapi32.dll", "/windows/system32/netapi32.dll"]

COPY --from=download ["/temp/msys64", "/msys64"]

# RUN bash -l -c "pacman -Syuu --needed --noconfirm --noprogressbar" && \
#     bash -l -c "pacman -Syu --needed --noconfirm --noprogressbar"
#    bash -l -c "rm -fr /C/Users/ContainerUser/* /var/cache/pacman/pkg/*"


RUN mklink /J C:\\msys64\\home\\ContainerUser C:\\Users\\ContainerUser && \
    setx HOME "C:\msys64\home\ContainerUser"

# RUN SETX PATH 
#"C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\bin;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl;%PATH%"

ENV MSYSTEM=MSYS
WORKDIR C:\\msys64\\home\\ContainerUser\\
# CMD ["bash", "-l"]
# Test application
RUN \
    ls \
        --version

RUN \
    bash \
        --version
RUN \
    sh \
        --version

