# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Bloaty macOS

permissions:
  contents: read
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/bloaty_macos.yml'

jobs:
  Fetch-Source:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Target Branches
        id: gittargets
        shell: bash
        run: |
          OS_REF=""
          APPS_REF=""
          # 
          # master
          REF="refs/heads/main"
          echo "Working with ref: $REF"
      - name: Checkout nuttx repo
        uses: actions/checkout@v4
        with:
          repository: simbit18/nuttx-testing-msys2
          # master
          ref:  main
          path: sources/nuttx-testing-msys2
          fetch-depth: 2
      - name: Checkout nuttx-testing-msys2 repo tags
        run: git -C sources/nuttx-testing-msys2 fetch --tags

      - name: Tar sources
        run: tar zcf sources.tar.gz sources

      - name: Archive Source Bundle
        uses: actions/upload-artifact@v4
        with:
          name: source-bundle
          path: sources.tar.gz
  bloaty_macos:
    needs: Fetch-Source
    permissions:
      contents: write
    runs-on: macos-latest
    env:
        namejob: macBloaty
    steps:
      - name: Download Source Artifact
        uses: actions/download-artifact@v4
        with:
          name: source-bundle
          path: .

      - name: Extract sources
        run: |
          tar zxf sources.tar.gz
          # ls -a source
      - name: System Information
        run: |
          uname -a
          bash --version
          gcc -v
          xcodebuild -version
          brew install dmd
          brew install dub
      - name: Restore Tools Cache
        id: cache-tools
        uses: actions/cache@v4
        env:
          cache-name: ${{ env.namejob }}-cache-tools
        with:
          path: ./sources/tools
          key: ${{ env.namejob }}-tools-${{ hashFiles('./sources/nuttx-testing-msys2/bloaty/exception_setjmp.c') }}
      - name: Export bloaty Repo SHA
        run: echo "bloaty_sha=`git -C sources/bloaty rev-parse HEAD`" >> $GITHUB_ENV

      # Released version of Cython has issues with Python 11. Set runner to use Python 3.10
      # https://github.com/cython/cython/issues/4500
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Builds
        run: |
          ##echo "::add-matcher::sources/nuttx/.github/gcc.json"
          ## export ARTIFACTDIR=`pwd`/buildartifacts
          #cd sources/nuttx/tools/ci
          # debug
          #./cibuild.sh -d -i -c -C -A -R testlist/${{matrix.boards}}.dat
          #./cibuild.sh -i -c -A -C -R testlist/${{matrix.boards}}.dat
          echo 'Build'
          cd sources/nuttx-testing-msys2/bloaty
          gcc ./exception_setjmp.c -o exception_setjmp
          ## ls -a $GITHUB_WORKSPACE/bloaty
          ./exception_setjmp
          ./bloaty.sh
          # echo 'source'
          # source sources/tools/env.sh
          echo 'PATH'
          echo "$GITHUB_PATH"
          echo "$PATH"
          ## bloaty -n 20 -d sections,symbols /exception_setjmp
      - name: Test Bloaty
        run: |
          ls -a ${{github.workspace}}
          ## echo "${{github.workspace}}/main/extern/crashpad/breakpad/win/" >> $GITHUB_PATH
          # bloaty --version

