name: Build of NuttX for Nucleo_F411re_nsh on MSYS2

permissions:
  ## Allow publishing of GitHub Release
  contents: write
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/MSYS2_Nucleo_F411re_nsh.yml'
env:
   ARM_URL: https://developer.arm.com/-/media/Files/downloads/gnu/12.3.rel1/binrel/
   ARM_NAME: arm-gnu-toolchain-12.3.rel1-mingw-w64-i686-arm-none-eabi

jobs:
  nuttx-arm-msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      with:
        repository: simbit18/nuttx
        ref: simbit18-ci
        path: nuttx
        fetch-depth: 1
      - name: Checkout nuttx repo tags
        run: git -C nuttx fetch --tags

      - name: Checkout apps repo
      - uses: actions/checkout@v4
      with:
        repository: simbit18/nuttx-apps
        ref: simbit18-ci
        path: apps
        fetch-depth: 1
      - name: Checkout nuttx repo tags
        run: git -C apps fetch --tags
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: false
          install: >-
            base-devel
            gcc
            gperf
            git
            python3
            ncurses-devel
            unzip
            zip
            tio
            zlib-devel
            cmake
            ninja
            python-pip 
            vim
            curl
        
      - name: pip3 install
        run: |
          echo 'pip3 install'
          uname
          pip3 install --root-user-action=ignore --no-cache-dir pyelftools cxxfilt kconfiglib

