name: Nuttx-master cygwin

permissions:
  ## Allow publishing of GitHub Release
  contents: read
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/cygwin_sim.yml'

jobs:
  nuttx-sim-cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash.exe --login --norc -eo pipefail -o igncr '{0}'
    env:
      SHELLOPTS: igncr
      CHERE_INVOKING: 1
      CYGWIN_NOWINPATH: 1
    steps:
    - name: Configure git
      run: |
        git config --global core.autocrlf input
      # shell: cmd
    - name: Checkout from git
      uses: actions/checkout@v4
      with: 
        submodules: 'true'
    # install cygwin and build tools
    - name: Install Cygwin
      uses: cygwin/cygwin-install-action@master
      with:
          platform: x86_64
          packages: >-
            coreutils
            make
            gcc-core
            gcc-g++
            gperf
            flex
            git
            bison
            byacc
            gdb
            unzip
            awk
            automake-1.15
            autoconf
            wget
            xxd
            libmpc-devel
            libncurses-devel
            libmpfr-devel
            libiconv-devel
            zlib-devel
            patch
            python3
            cmake
            ninja
            curl
            python-pip
        
    - name: pip3 install
      run: |
          echo 'pip3 install'
          uname
          pip3 install --root-user-action=ignore --no-cache-dir pyelftools cxxfilt kconfiglib
    - name: Check ENV
      # shell: cmd
      run: |
          echo "PATH=%PATH%"
          ls -a
    - name: Install kconfig-frontends
      shell: C:\cygwin\bin\bash.exe --noprofile --norc -eo pipefail '{0}'
      run: |
          export PATH=/usr/bin:$(cygpath ${SYSTEMROOT})/system32
          export MAKEFLAGS=-j$(nproc)
          echo "$GITHUB_PATH"
          echo "$PATH"
          uname -a
          gcc -v
          echo 'Install kconfig-frontends'
          curl -L https://bitbucket.org/nuttx/tools/get/master.tar.gz -o nuttx-tools.tar.gz
          mkdir nuttx-tools
          tar xvzf nuttx-tools.tar.gz --strip-components=1 -C nuttx-tools
          cd nuttx-tools/kconfig-frontends
          ./configure --disable-kconfig --disable-nconf --disable-qconf \
                      --disable-gconf --disable-mconf --disable-static \
                      --disable-shared --disable-L10n
          touch aclocal.m4 Makefile.in
          make install

    - name: Install genromfs
      shell: C:\cygwin\bin\bash.exe --noprofile --norc -eo pipefail '{0}'
      run: |
          echo 'Install genromfs'
          cd nuttx-tools
          tar xzf genromfs-0.5.2.tar.gz
          cd genromfs-0.5.2
          make install PREFIX=/opt/nuttxenv
    - name: Copy NXTOOL GENROMFS and clean source files
      run: |
          echo 'Copy NXTOOL GENROMFS and clean source files'
          cp /opt/nuttxenv/usr/bin/kconfig-conf.exe /usr/bin
          # cp /opt/nuttxenv/usr/bin/kconfig-mconf.exe /usr/bin
          cp /opt/nuttxenv/usr/bin/kconfig-tweak /usr/bin
          cp /opt/nuttxenv/usr/bin/genromfs.exe /usr/bin
          rm -rf nuttx-tools genromfs-0.5.2
          ls -a
          
    - name: Checkout Source Files
      run: |
          echo 'Checkout Source Files'
          mkdir nuttxspace
          ls -a
          cd nuttxspace
          git clone https://github.com/apache/incubator-nuttx nuttx
          git clone https://github.com/apache/incubator-nuttx-apps apps
          ## curl -L https://www.apache.org/dyn/closer.lua/nuttx/12.0.0/apache-nuttx-12.0.0.tar.gz?action=download -o nuttx.tar.gz
          ## curl -L https://www.apache.org/dyn/closer.lua/nuttx/12.0.0/apache-nuttx-apps-12.0.0.tar.gz?action=download -o apps.tar.gz
          ## tar zxf nuttx.tar.gz --one-top-level=nuttx --strip-components 1
          ## tar zxf apps.tar.gz --one-top-level=apps --strip-components 1
          ## ls -a
          ## cd nuttx
          ls -a

    - name: Build
      run: |
          echo 'Build'

          ## Move to nuttx
          cd nuttxspace/nuttx
          ls -a

          ## Show the GCC version
          gcc -v
          ## ls -a ../../
          ## cp -f ../../fix/1200/defconfig boards/sim/sim/sim/configs/nsh/defconfig
          ## cp -f ../../fix/1200/sim_hostmisc.c arch/sim/src/sim/posix/sim_hostmisc.c
          ## cp -f ../../fix/1200/lib_exit.c libs/libc/stdlib/lib_exit.c
          
          ## Configure the build
          ./tools/configure.sh -c sim:nsh
          
          ## mkdir nuttxmsys2
          
          ## Preserve the build config
          ## cp .config nuttxmsys2/nuttx.config
          make -j 4
          ls -a
          ## cp nuttx.exe nuttxmsys2/nuttx.exe
          ## cp System.map nuttxmsys2/System.map
          ## cp /usr/bin/msys-2.0.dll nuttxmsys2/msys-2.0.dll
          ## cp /usr/bin/msys-z.dll nuttxmsys2/msys-z.dll
          ## zip -r nuttxmsys2.zip nuttxmsys2
          
