#publish your docker image to github container registry
name: Docker-Nano-Publish
on:
  workflow_dispatch:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths:
      - 'docker/winnano/**'
      - '.github/workflows/docker_wnano_publish.yml'
env:
   REGISTRY: ghcr.io
   IMAGE_NAME: 'docker-nano-msys2'

concurrency:
  group: docker-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
    build:
      runs-on: windows-latest
      env:
        IMAGE_TAG: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Pre-build Disk Stats
          run: |
           df -h
        # - name: Build the WinNano-nuttx-docker Docker image
          # run: |
           docker build ./docker/winnano --tag ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
           docker run ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
           docker push ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
        - name: Push Docker image
          uses: docker/build-push-action@v6
          with:
            context: docker/winnano
            platforms: linux/amd64
            push: ${{ github.ref == 'refs/heads/master' }}
            tags: ${{ env.IMAGE_TAG }}
          ## uses: docker/build-push-action@v6
          ## with:
          ##  context: docker/winnano
          ##  push: ${{ github.ref == 'refs/heads/master' }}
          ##  tags: ${{ env.IMAGE_TAG }}
        - name: Post-build Disk Stats
          if: always()
          run: |
           df -h