#publish your docker image to github container registry
name: Docker-Win-Publish
on:
  workflow_dispatch:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - master
    paths:
      - 'docker/winnano/**'
      - '.github/workflows/docker_wnano_publish.yml'
env:
   REGISTRY: ghcr.io
   IMAGE_NAME: 'docker-ci-msys2'

concurrency:
  group: docker-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
    build:
      runs-on: windows-latest
      env:
        IMAGE_TAG: ghcr.io/${{ github.repository }}/docker-ci-msys2
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3

          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Pre-build Disk Stats
          run: |
           df -h
        - name: Build the WinNano-nuttx-docker Docker image
          uses: docker/build-push-action@v5
          with:
            context: docker/winnano
            push: ${{ github.ref == 'refs/heads/master' }}
            tags: ${{ env.IMAGE_TAG }}
        - name: Post-build Disk Stats
          if: always()
          run: |
           df -h