# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Docker-Inspect-test

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docker_inspect.yml'
env:
   REGISTRY: ghcr.io
permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ghcr.io/simbit18/nuttx-testing-ci/apache-nuttx-ci-linux:latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # -
        # name: Build
        # uses: docker/build-push-action@v6
        # with:
          # context: tools/ci/docker/linux
          # load: true
          # tags: anuttx:latest
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Inspect
        run: |
          docker images
          # docker image inspect IMAGE ${{ env.IMAGE_NAME }}
      -
        name: Hystory
        run: |
          docker history apache-nuttx-ci-linux:latest
          # docker pull ghcr.io/simbit18/nuttx-testing-ci/apache-nuttx-ci-linux:latest
