#publish your docker image to github container registry
name: Docker-Alpine-Publish
on:
  workflow_dispatch:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths:
      - 'docker/winnano/**'
      - '.github/workflows/docker_alpine_publish.yml'
env:
   REGISTRY: ghcr.io
   IMAGE_NAME: 'docker-test-alpine'

concurrency:
  group: docker-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:
    build:
      runs-on: ubuntu-latest
      env:
        IMAGE_TAG: ghcr.io/${{ github.repository }}/docker-test-alpine
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Pre-build Disk Stats
          run: |
           df -h
        - name: Build
          run: |
            docker build
            --build-arg VERSION=3.20.2
            -t ghcr.io/${{ github.repository_owner }}/docker-test-alpine:last
            ./docker/alpine
        - name: Push Docker image
          run: |
            docker push ghcr.io/${{ github.repository_owner }}/docker-test-alpine --all-tags
        - name: Tag latest Alpine version
          run: |
            docker tag ghcr.io/${{ github.repository_owner }}/docker-test-alpine:last ghcr.io/${{ github.repository_owner }}/docker-test-alpine
        - name: Post-build Disk Stats
          if: always()
          run: |
           df -h