name: kconfig MSYS2 MINGW64

permissions:
  ## Allow publishing of GitHub Release
  contents: write
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/kconfig.yml'

jobs:
  nuttx-kconfig-msys2-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        btype:
          - Release
        msystem:
          # - CLANG64
          - MINGW64
          # - MINGW32
          # - MSYS
          # - UCRT64
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: false
          install: >-
            bison
            flex
            git
            zip

          pacboy: >-
            cc:p
            gperf:p
            cmake:p
            ninja:p
            curl:p
            gcc-libs:p
            gettext-tools:p
            ncurses:p

      - name: Checkout Source Files
        run: |
          echo 'Checkout Source Files'
          cmake --help
          env
          gcc -v
          mkdir kconfigspace
          ls -a
          cd kconfigspace
          git clone --single-branch --branch msys2-mingw64 https://github.com/simbit18/kconfig-frontends-win.git
          ls -a
          cd kconfig-frontends-win
          ls -a
          # old ----------------
          # mkdir build
          # cd build
          # cmake -GNinja ..
          # cmake --build .
          # ls -a
          # --------------------------
          # cmake -G "MinGW Makefiles" ..
          cmake -B build -GNinja
          cmake --build build -v
          mkdir kconfig-frontends-win32
          cp build/bin/kconfig-mconf.exe kconfig-frontends-win32/kconfig-mconf.exe
          cp build/bin/kconfig-conf.exe kconfig-frontends-win32/kconfig-conf.exe
          cp utils/kconfig-tweak.bat kconfig-frontends-win32/kconfig-tweak.bat
          cp /usr/bin/libsystre-0.dll kconfig-frontends-win32/libsystre-0.dll
          cp /usr/bin/libtre-5.dll kconfig-frontends-win32/libtre-5.dll
          zip -r kconfig-frontends-win32.zip kconfig-frontends-win32
      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Publish the GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: kconfig-frontends-win-${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          generate_release_notes: false
          files: |
            kconfigspace/kconfig-frontends-win/kconfig-frontends-win32.zip
