## Building the Nuttx Toolchain - Buildroot

name: Building the Nuttx Toolchain Buildroot

permissions:
  ## Allow publishing of GitHub Release
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/nuttx_buildroot.yml'

jobs:
  # Label of the container job
  build:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:

    - name: Install Build Tools
      run: |
        sudo apt -y update
        sudo apt -y install \
        bison flex gettext texinfo libncurses5-dev libncursesw5-dev \
        gperf automake libtool pkg-config build-essential gperf genromfs \
        libgmp-dev libmpc-dev libmpfr-dev libisl-dev binutils-dev libelf-dev \
        libexpat-dev gcc-multilib g++-multilib u-boot-tools util-linux \
        kconfig-frontends \
        wget u-boot-tools

    - name: Clone the NuttX buildroot module
      run: |
        mkdir -p nuttx-git
        git clone --depth 1 https://bitbucket.org/nuttx/buildroot.git buildroot
        ls -a
        mkdir -p archive
        cd buildroot
        ls -a
        cp configs/arm-defconfig .config
        make
    # - name: Checkout Source Files
      # run:  |
        # mkdir nuttx
        # cd nuttx
        # git clone --depth 1 https://github.com/apache/nuttx nuttx
        # git clone --depth 1 https://github.com/apache/nuttx-apps apps

    - name: Build
      run: |
        # # ## Add toolchain to PATH
        # # cd nuttx/nuttx

        # # ## Dump the git hash
        # # hash1=`git rev-parse HEAD`
        # # pushd ../apps
        # # hash2=`git rev-parse HEAD`
        # # popd
        # # echo NuttX Source: https://github.com/apache/nuttx/tree/$hash1 >nuttx.hash
        # # echo NuttX Apps: https://github.com/apache/nuttx-apps/tree/$hash2 >>nuttx.hash
        # # cat nuttx.hash

        # # ## Show the GCC version
        # # gcc -v

        # # ## Configure the build
        # # tools/configure.sh -l sim:nsh

        # # ## Preserve the build config
        # # cp .config nuttx.config

        # # ## Run the build
        # # make

        # # ## Export the Binary Image to nuttx.bin
        # # objcopy \
          # # -O binary \
          # # nuttx \
          # # nuttx.bin


    # - name: Upload Build Outputs as Artifacts
      # uses: actions/upload-artifact@v4
      # with:
        # name: nuttx.zip
        # path: |
          # nuttx/nuttx/nuttx*
          # nuttx/nuttx/initrd
          # nuttx/nuttx/init.S

    # - name: Zip Build Outputs for GitHub Release
      # run: |
        # cd nuttx/nuttx
        # zip  nuttx*

    # - name: Get Current Date
      # id: date
      # run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    # - name: Publish the GitHub Release
      # uses: softprops/action-gh-release@v2
      # with:
        # tag_name: testaction-${{ steps.date.outputs.date }}
        # draft: false
        # prerelease: false
        # generate_release_notes: false
        # files: |
          # nuttx/nuttx/nuttx
          # nuttx/nuttx/nuttx.config
          # nuttx/nuttx/nuttx.manifest
          # nuttx/nuttx/nuttx.hash
