name: Rust MSYS2

permissions:
  ## Allow publishing of GitHub Release
  contents: write
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/rust.yml'

jobs:
  rust-msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: false
          install: >-
            base-devel
            gcc
            gperf
            git
            python3
            ncurses-devel
            unzip
            zip
            tio
            libffi-devel
            zlib-devel
            openssl-devel
            pkg-config
            cmake
            ninja
            python-pip 
            vim
            curl
        
      - name: pip3 install
        run: |
          echo 'pip3 install'
          uname
          pip3 install --root-user-action=ignore --no-cache-dir pyelftools cxxfilt kconfiglib

      - name: Build
        run: |
          echo 'Build'

          ## Move to nuttx
          ## cd nuttxspace/nuttx
          mkdir rust-tools
          ls -a

          ## Show the GCC version
          gcc -v
          ls -a 
          cp -f rust/rust.sh rust-tools/rust.sh
          cd rust-tools
          ls -a
          ./rust.sh
          ls -a
          
         
