# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Testlight

permissions:
  contents: read
on: 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/Testlight.yml'

jobs:
  build_alpine:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: alpine:latest

    steps:

      - name: Install Build Tools
        run:  |
          apk --no-cache --update add \
          bash
      - name: Install Dependencies
        run: bash --version
      - name: Build
        run: |
          bash --version
          ## bash scripts/build.sh --bundle --debug --forcefallback $ARCH
